repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        language: system
        types: [swift]
        args: [--config, .swiftformat, --swiftversion, "5.9"]
        # Allow committing even if files were modified by this hook
        always_run: true
        pass_filenames: true
        files: \.(swift)$
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint lint --config .swiftlint.yaml
        language: system
        files: \.swift$
        types: [file, swift]
        pass_filenames: true
        require_serial: true
        stages: [commit]
        # Don't fail on warnings, only on errors
        args: [--quiet]