# Default rules are enabled by default
disabled_rules:
  - trailing_whitespace # Trailing whitespace is sometimes useful
  - line_length # Line length is handled by the formatter

opt_in_rules:
  - empty_count # Prefer isEmpty over count == 0
  - empty_string # Prefer isEmpty over string == ""
  - explicit_init # Prefer using explicit init when type is ambiguous
  - closure_spacing # Closure expressions should have a single space inside each brace
  - force_unwrapping # Force unwrapping should be avoided

# Paths to include during linting
included:
  - AtomicArch

# Paths to ignore during linting
excluded:
  - Pods
  - AtomicArch/Generated
  - AtomicArchTests
  - AtomicArchUITests
  - vendor
  - fastlane
  - Carthage
  - DerivedData

# Customize rules
identifier_name:
  excluded:
    - id
    - to
    - at
    - of
    - up
    - on
    - no
    - URL
  
type_name:
  min_length: 3
  max_length: 50

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 350
  error: 400

nesting:
  type_level:
    warning: 3

reporter: "xcode"