name: iOS CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies -project AtomicArch.xcodeproj

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Clean & Build
        run: |
          xcodebuild clean build \
            -project AtomicArch.xcodeproj \
            -scheme AtomicArch \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' | xcpretty

      - name: Run Tests
        run: |
          xcodebuild clean test \
            -project AtomicArch.xcodeproj \
            -scheme AtomicArch \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest' \
            -enableCodeCoverage YES | xcpretty

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
