name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: SwiftLint
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install SwiftLint
        run: brew install swiftlint
        
      - name: Run SwiftLint
        run: swiftlint lint --config .swiftlint.yaml
  
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      SCHEME: AtomicArch
      PLATFORM: iOS
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
          
      - name: Cache Swift packages
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
            
      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies -project AtomicArch.xcodeproj
          
      - name: Install xcpretty
        run: gem install xcpretty

      - name: Build and test
        run: |
          xcodebuild clean test \
            -project AtomicArch.xcodeproj \
            -scheme ${{ env.SCHEME }} \
            -destination 'platform=${{ env.PLATFORM }} Simulator,name=iPhone 16 Pro,OS=latest' \
            -enableCodeCoverage YES | xcpretty
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: |
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult